export const messageMap = new Map([
    ['name', { default:'姓名', skill:'技能名字' }],
    ['avatar', { default: '头像' }],
    ['expectPosition', { default: '期望职位' }],
    ['expectCity', { default: '期望城市' }],
    ['expectIndustry', { default: '期望行业' }],
    ['expectCategory', { default: '工作性质' }],
    ['school', { default: '学校名称' }],
    ['major', { default: '专业名称' }],
    ['degree', { default: '学历' }],
    ['startDate', { default: '开始日期' }],
    ['endDate', { default: '结束日期' }],
    ['isFullTime', { default: '是否全日制' }],
    ['company', { default: '公司名称' }],
    ['position', { default: '职位名称' }],
    ['salary', { default: '薪资' }],
    ['description', { default: '内容描述' }],
    ['title', { default: '项目名称'}],
    ['role', { default: '担任角色' }],
    ['demoUrl', { default: '项目链接' }],
    ['techStack', { default: '技术栈' }],
    ['time', { default: '掌握时间' }],
    ['level', { default: '技能等级' }],
    ['language', { default: '语种' }],
    ['LSLevel', { default: '听说能力' }],
    ['literacyLevel', { default: '读写能力' }],
    ['organization', { default: '机构名称' }],
    ['course', { default: '课程名称' }],
    ['url', { default: '作品地址' }],
]);
export const triggerMap = new Map([
    ['blur','输入'],
    ['change','选择'],
    ['click','点击'],
    ['submit','提交'],
    ['reset','重置'],
]);